### ISSUE TITLE
Redirect directive 

### ISSUE THREAD

**Issue by ambienthack** [asimlqt/php-google-oauth#2]
Do we really need this line inside apache config?

```
 Redirect 301 / http://google-auth.local
```

**Comment by asimlqt** [comment]
Yes, because Google will not allow you to set an oauth redirect url to anything but a valid domain and localhost for development.

That redirect forwards onto the actual virtual host that was setup in the docs to handle the response.

If you set it up in such a way that you're only using localhost and not a separate virtual host then in that case it's not needed.
